name: quest_peak
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: 0.13.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  flutter_riverpod: ^2.0.2
  geolocator: ^9.0.2
  toggle_switch: ^2.0.1

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_database: ^10.0.7
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/quest/
    - assets/icon/
  #   - assets/quest/Inscription.jpg
  #   - assets/quest/Light.jpg
  #   - assets/quest/Plate.jpg
  #   - assets/quest/Products.jpg
  #   - assets/quest/Programming.jpg
  #   - assets/quest/Suffer.jpg
